/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StagingRouteImport } from './routes/staging'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesSunsetSmilesDentistryRouteImport } from './routes/sites.sunset-smiles-dentistry'
import { Route as SitesNorthBeachTrattoriaRouteImport } from './routes/sites.north-beach-trattoria'
import { Route as SitesMamaMiaPizzeriaRouteImport } from './routes/sites.mama-mia-pizzeria'
import { Route as SitesGoldenGateGrillRouteImport } from './routes/sites.golden-gate-grill'
import { Route as SitesChicCutsSalonRouteImport } from './routes/sites.chic-cuts-salon'

const StagingRoute = StagingRouteImport.update({
  id: '/staging',
  path: '/staging',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSunsetSmilesDentistryRoute =
  SitesSunsetSmilesDentistryRouteImport.update({
    id: '/sites/sunset-smiles-dentistry',
    path: '/sites/sunset-smiles-dentistry',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitesNorthBeachTrattoriaRoute =
  SitesNorthBeachTrattoriaRouteImport.update({
    id: '/sites/north-beach-trattoria',
    path: '/sites/north-beach-trattoria',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitesMamaMiaPizzeriaRoute = SitesMamaMiaPizzeriaRouteImport.update({
  id: '/sites/mama-mia-pizzeria',
  path: '/sites/mama-mia-pizzeria',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesGoldenGateGrillRoute = SitesGoldenGateGrillRouteImport.update({
  id: '/sites/golden-gate-grill',
  path: '/sites/golden-gate-grill',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesChicCutsSalonRoute = SitesChicCutsSalonRouteImport.update({
  id: '/sites/chic-cuts-salon',
  path: '/sites/chic-cuts-salon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/staging': typeof StagingRoute
  '/sites/chic-cuts-salon': typeof SitesChicCutsSalonRoute
  '/sites/golden-gate-grill': typeof SitesGoldenGateGrillRoute
  '/sites/mama-mia-pizzeria': typeof SitesMamaMiaPizzeriaRoute
  '/sites/north-beach-trattoria': typeof SitesNorthBeachTrattoriaRoute
  '/sites/sunset-smiles-dentistry': typeof SitesSunsetSmilesDentistryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/staging': typeof StagingRoute
  '/sites/chic-cuts-salon': typeof SitesChicCutsSalonRoute
  '/sites/golden-gate-grill': typeof SitesGoldenGateGrillRoute
  '/sites/mama-mia-pizzeria': typeof SitesMamaMiaPizzeriaRoute
  '/sites/north-beach-trattoria': typeof SitesNorthBeachTrattoriaRoute
  '/sites/sunset-smiles-dentistry': typeof SitesSunsetSmilesDentistryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/staging': typeof StagingRoute
  '/sites/chic-cuts-salon': typeof SitesChicCutsSalonRoute
  '/sites/golden-gate-grill': typeof SitesGoldenGateGrillRoute
  '/sites/mama-mia-pizzeria': typeof SitesMamaMiaPizzeriaRoute
  '/sites/north-beach-trattoria': typeof SitesNorthBeachTrattoriaRoute
  '/sites/sunset-smiles-dentistry': typeof SitesSunsetSmilesDentistryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/staging'
    | '/sites/chic-cuts-salon'
    | '/sites/golden-gate-grill'
    | '/sites/mama-mia-pizzeria'
    | '/sites/north-beach-trattoria'
    | '/sites/sunset-smiles-dentistry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/staging'
    | '/sites/chic-cuts-salon'
    | '/sites/golden-gate-grill'
    | '/sites/mama-mia-pizzeria'
    | '/sites/north-beach-trattoria'
    | '/sites/sunset-smiles-dentistry'
  id:
    | '__root__'
    | '/'
    | '/staging'
    | '/sites/chic-cuts-salon'
    | '/sites/golden-gate-grill'
    | '/sites/mama-mia-pizzeria'
    | '/sites/north-beach-trattoria'
    | '/sites/sunset-smiles-dentistry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StagingRoute: typeof StagingRoute
  SitesChicCutsSalonRoute: typeof SitesChicCutsSalonRoute
  SitesGoldenGateGrillRoute: typeof SitesGoldenGateGrillRoute
  SitesMamaMiaPizzeriaRoute: typeof SitesMamaMiaPizzeriaRoute
  SitesNorthBeachTrattoriaRoute: typeof SitesNorthBeachTrattoriaRoute
  SitesSunsetSmilesDentistryRoute: typeof SitesSunsetSmilesDentistryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staging': {
      id: '/staging'
      path: '/staging'
      fullPath: '/staging'
      preLoaderRoute: typeof StagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/sunset-smiles-dentistry': {
      id: '/sites/sunset-smiles-dentistry'
      path: '/sites/sunset-smiles-dentistry'
      fullPath: '/sites/sunset-smiles-dentistry'
      preLoaderRoute: typeof SitesSunsetSmilesDentistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/north-beach-trattoria': {
      id: '/sites/north-beach-trattoria'
      path: '/sites/north-beach-trattoria'
      fullPath: '/sites/north-beach-trattoria'
      preLoaderRoute: typeof SitesNorthBeachTrattoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/mama-mia-pizzeria': {
      id: '/sites/mama-mia-pizzeria'
      path: '/sites/mama-mia-pizzeria'
      fullPath: '/sites/mama-mia-pizzeria'
      preLoaderRoute: typeof SitesMamaMiaPizzeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/golden-gate-grill': {
      id: '/sites/golden-gate-grill'
      path: '/sites/golden-gate-grill'
      fullPath: '/sites/golden-gate-grill'
      preLoaderRoute: typeof SitesGoldenGateGrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/chic-cuts-salon': {
      id: '/sites/chic-cuts-salon'
      path: '/sites/chic-cuts-salon'
      fullPath: '/sites/chic-cuts-salon'
      preLoaderRoute: typeof SitesChicCutsSalonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StagingRoute: StagingRoute,
  SitesChicCutsSalonRoute: SitesChicCutsSalonRoute,
  SitesGoldenGateGrillRoute: SitesGoldenGateGrillRoute,
  SitesMamaMiaPizzeriaRoute: SitesMamaMiaPizzeriaRoute,
  SitesNorthBeachTrattoriaRoute: SitesNorthBeachTrattoriaRoute,
  SitesSunsetSmilesDentistryRoute: SitesSunsetSmilesDentistryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
